### PR TITLE
Added method suspend()

### LINKED ISSUE #10: New Method: suspend()
The call to this method must “suspend” or “pause” the applied effects (prefix(), suffix() and wrap()) and it’s influence will finish with the call to end() method by restoring the previously added effects. This would be useful if you want to append a large amount of text and you want to temporarily turn off the effects you’ve already configured.
The following sample code assumes that you have implemented all the nice to have methods.
```js
var sb = new StringBuilder(),
    sections = ['section 1', 'section 2', 'section 3'];
sb
	.suffix('\n')
	.cat('<body>')
	.prefix('  ')
	.wrap('<section>', '</section>')
	.each(sections, function(section, index){
		this
			.cat('<h1>', section, '</h1>', function(){
				this
					.suspend()
					.wrap('<p>', '</p>')
					.cat('first paragraph')
					.cat('second paragraph')
					.end(2);
			})	
	})
	.end(2)
	.cat('</body>')
```

And if you did it well this is the output you must get,
```html
<body>
  <section><h1>section 1</h1><p>first paragraph</p><p>second paragraph</p></section>
  <section><h1>section 2</h1><p>first paragraph</p><p>second paragraph</p></section>
  <section><h1>section 3</h1><p>first paragraph</p><p>second paragraph</p></section>
</body>
```

### PR DESCRIPTION
**Pull request by islas27**
- Added method suspend()
- Added unit tests in suspend.spec.js
- Added unit test for additional functionality in end()
- Added documentation & examples

Closes #10

### CODE REVIEW

**Comment by islas27** [comment]
@ryanez based on the documentation of the requirements, I developed the function this way, what do you think of it?

**Comment by ryanez** [comment]
Looks good, but it would also be good if you implement on the tests the exercises provided on requirements, they make a little more sense than "abcdefg" and test more features.

**Comment by islas27** [comment]
Righto, will do!

**Comment by islas27** [comment]
Alright, added a more real case as a test for `suspend()`, and kept sending a new instance of the builder during `cat()` when executing functions. What do you think of it now? @ryanez 

-WIP: Still missing docs and examples

**Comment by islas27** [comment]
Completed the documentation and added an example. Feel free to comment on it @ryanez

**Comment by ryanez** [comment]
LGTM 👍  you can merge it

**Pull request merged**
